---
title: "Manuscript 2: Gastric aspiration and the lung microbiome"
output: html_document
---


# LEFT LUNG only
## Part 1
* Samples
    + SLU1 through 11 (control)
    + WLU1 through 12 (whole gastric fluid, group #1)
    + ILU1 through 12 (irradiated gastric fluid)
* Analysis
    + with SLU group
        + NMDS plot
        + LEfSe 
    + **without** SLU group
        + NMDS plot
        + LEfSe 

## Part 2
* Samples
    + WLU1 through 12 (whole gastric fluid, cohort #1)
    + WLU13 through 24 (whole gastric fluid, cohort #2)
* Analysis
    + NMDS plot
    + LEfSe

## Part 3
* Samples
    + SLU1 through 11 (control)
    + WLU13 through 24 (whole gastric fluid, cohort #2)
    + ASWLU1 through 12 (whole gastric fluid plus antibiotics)
* Analysis
    + SLU and WLU
        + NMDS plot
        + LEfSe 
    + WLU and ASWLU
        + NMDS plot
        + LEfSe 

# RIGHT lung PAIRED with LEFT lung from same animal (e.g. SLU1 paired with SRU1) 
## Part 1
* Samples
    + SLU1 through 11 (control)
    + SRU1 through 11
    + WLU1 through 12 (whole gastric fluid, group #1)
    + WRU1 through 12
    + ILU1 through 12 (irradiated gastric fluid)
    + IRU1 through 12
* Analysis
    + For each right and left lung PAIR (e.g. SLU1 and SRU1)
        + NMDS plot
        + LEfSe
    + For RIGHT LUNG samples only including SRU group, then excluding SRU group
        + NMDS plot
        + LEfSe
    + For RIGHT LUNG samples only excluding SRU group
        + NMDS plot
        + LEfSe

## Part 2
* Samples
    + WRU1 through 12 (whole gastric fluid, cohort #1)
    + WRU13 through 24 (whole gastric fluid, cohort #2)
* Analysis
    + NMDS plot
    + LEfSe 

## Part 3
* Samples
    + SLU1 through 11 (control)
    + SRU1 through 11
    + WLU13 through 24 (whole gastric fluid, cohort #2)
    + WRU13 through 24
    + ASWLU1 through 12 (whole gastric fluid plus antibiotics)
    + ASWRU1 through 12
* Analysis
    + For each right and left lung PAIR (e.g. SLU1 and SRU1)
        + NMDS plot
        + LEfSe
    + For RIGHT LUNG samples only, SRU and WRU groups
        + NMDS plot
        + LEfSe
    + For RIGHT LUNG samples only, WRU and ASWRU groups
        + NMDS plot
        + LEfSe
