---
title: "Manuscript 2: Gastric aspiration and the lung microbiome, additional analyses"
output: 
  html_document:
    toc: true # table of content 
    toc_float:
      collapsed: true
      smooth_scroll: false
    depth: 3  # upto three depths of headings (specified by #, ## and ###)
    number_sections: true  ## if you want number sections at each table header
    theme: united  # many options for theme, this one is my favorite.
    highlight: tango  # specifies the syntax highlighting style
---

<!---
From commandline run with the following:
Rscript -e "library(knitr); rmarkdown::render('aspiration_analysis_right_and_left_lungs.Rmd')"
-->

```{r load_libraries, echo=FALSE, results='hide'}

source("analysis_functions.R")

## Load Libraries
suppressPackageStartupMessages(library("phyloseq"))
suppressPackageStartupMessages(library("ggplot2"))
suppressPackageStartupMessages(library("dplyr"))
# suppressPackageStartupMessages(library("magrittr"))
# suppressPackageStartupMessages(library("tools"))

## Load Data
bacteria_ps.rds = file.path("workspace", "bacteria_ps.rds")
if (!file.exists(bacteria_ps.rds)){
  source("preprocess_phyloseq.R")
}
bacteria.ps = readRDS(bacteria_ps.rds)
```

# Mean and median relative abundance of Romboutsia and Turicibacter
## Romboutsia

```{r}
aspiration.ps = subset_samples(bacteria.ps, antibiotic == "none")
aspiration.ps.rel  = transform_sample_counts(aspiration.ps, function(x) x / sum(x) )
# as.tibble(rowSums(otu_table(aspiration.ps.rel)))

aspiration.ps.rel.romboutsia = subset_taxa(aspiration.ps.rel,Genus=="Romboutsia")
print(aspiration.ps.rel.romboutsia)
plot_bar(aspiration.ps.rel.romboutsia)
```

```{r}
as.tibble(rowSums(otu_table(aspiration.ps.rel.romboutsia)))
plot_bar(aspiration.ps.rel.romboutsia, x="group")

# otu_table(aspiration.ps.rel.romboutsia)
romb_abund = psmelt(aspiration.ps.rel.romboutsia) %>% 
  group_by(SampleID,group) %>%
  summarize(romb_frac = sum(Abundance))

ggplot(romb_abund, aes_string("SampleID", "romb_frac")) +
  geom_bar(stat = "identity", position = "stack", color = "black")
```

```{r}
romb_abund %>% 
  group_by(group) %>%
  summarize(romboutsia_frac_mean = mean(romb_frac),
            romboutsia_frac_median = median(romb_frac))
```

```{r}
ggplot(romb_abund, aes(group, romb_frac)) +
  geom_boxplot() + 
  geom_jitter(width = 0.1) +
  labs(y = "Romboutsia Proportional Abundance")
```


## Turicibacter

```{r}
aspiration.ps.rel.Turicibacter = subset_taxa(aspiration.ps.rel,Genus=="Turicibacter")
print(aspiration.ps.rel.Turicibacter)
plot_bar(aspiration.ps.rel.Turicibacter)
```

```{r}
as.tibble(rowSums(otu_table(aspiration.ps.rel.Turicibacter)))
plot_bar(aspiration.ps.rel.Turicibacter, x="group")

# otu_table(aspiration.ps.rel.Turicibacter)
turi_abund = psmelt(aspiration.ps.rel.Turicibacter) %>% 
  group_by(SampleID,group) %>%
  summarize(turi_frac = sum(Abundance))

ggplot(turi_abund, aes_string("SampleID", "turi_frac")) +
  geom_bar(stat = "identity", position = "stack", color = "black")
```

```{r}
turi_abund %>% 
  group_by(group) %>%
  summarize(Turicibacter_frac_mean = mean(turi_frac),
            Turicibacter_frac_median = median(turi_frac))
```

```{r}
ggplot(turi_abund, aes(group, turi_frac)) +
  geom_boxplot() + 
  geom_jitter(width = 0.1) +
  labs(y = "Turicibacter Proportional Abundance")
```

