#!/usr/bin/env bash

RMARKDOWN_FILE="aspiration_analysis_right_and_left_lungs.Rmd"
LEFSE_DIR="workspace/lefse_aspiration_left_right"

Rscript preprocess_phyloseq.R

# Run RMARKDOWN_FILE the first time to generate lefse input
Rscript -e "library(knitr); rmarkdown::render('${RMARKDOWN_FILE}')"

# Run LefSE
ls -1 ${LEFSE_DIR}/*.in | xargs -n1 ./run_lefse.sh

# Run RMARKDOWN_FILE again to embed figures generated by lefse
Rscript -e "library(knitr); rmarkdown::render('${RMARKDOWN_FILE}')"
