#!/usr/bin/env bash
# Based on https://bitbucket.org/nsegata/lefse/raw/ee1653ca297801562a3118aa606d063085be20d8/example/run.sh




RMARKDOWN_FILE="aspiration_analysis.Rmd"
LEFSE_DIR="workspace/lefse_aspiration"

Rscript preprocess_phyloseq.R

# Run RMARKDOWN_FILE the first time to generate lefse input
Rscript -e "library(knitr); rmarkdown::render('${RMARKDOWN_FILE}')"

# Run LefSE
ls -1 ${LEFSE_DIR}/*.in | xargs -n1 ./run_lefse.sh

# Run RMARKDOWN_FILE again to embed figures generated by lefse
Rscript -e "library(knitr); rmarkdown::render('${RMARKDOWN_FILE}')"
