DOCKER_IMAGE_TAG="DI_antibiotic_manuscript_rc1"
DOCKER_IMAGE_NAME="granek/rat_lung_microbiome"
DOCKER_IMAGE="${DOCKER_IMAGE_NAME}:${DOCKER_IMAGE_TAG}"

DOCKER_MNTPOINT="$HOME/parker_rat_lung"
WORKSPACE_MNTPOINT="$DOCKER_MNTPOINT/workspace"
DATA_MNTPOINT="$DOCKER_MNTPOINT/raw_data"

PORT_NUMBER=8786

echo $DOCKER_IMAGE
